#!/usr/bin/env bash

set -euo pipefail

RELEASE_ASSET_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="${DEPLOY_DIR:-/opt/lobechat-main}"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.prod.yml}"
ENV_FILE="${ENV_FILE:-.env}"
RELEASE_ENV_FILE="${RELEASE_ENV_FILE:-$RELEASE_ASSET_DIR/release.env}"
RELEASE_CONFIG_FILE="${RELEASE_CONFIG_FILE:-$RELEASE_ASSET_DIR/release-config.env}"
RELEASE_STATE_FILE="${RELEASE_STATE_FILE:-$RELEASE_ASSET_DIR/release-state.env}"
APP_CONTAINER="${APP_CONTAINER:-lobechat-app}"
SEARXNG_CONTAINER="${SEARXNG_CONTAINER:-lobechat-searxng}"

cd "$DEPLOY_DIR"

if [[ -f "$RELEASE_ENV_FILE" ]]; then
  set -a
  # release.env is generated by the local packaging script and contains only
  # an image reference, digest, commit, and migration identifiers.
  # shellcheck disable=SC1090
  source "$RELEASE_ENV_FILE"
  set +a
fi

TARGET_IMAGE="${TARGET_IMAGE:-${LOBECHAT_IMAGE:-}}"
TARGET_DIGEST="${TARGET_DIGEST:-${LOBECHAT_IMAGE_DIGEST:-}}"

fail() {
  echo "FAILED: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "missing command: $1"
}

require_file() {
  [[ -f "$1" ]] || fail "missing required file: $DEPLOY_DIR/$1"
}

read_env() {
  local key="$1"
  awk -F= -v key="$key" '
    $1 == key { value = substr($0, index($0, "=") + 1) }
    END { if (value != "") print value }
  ' "$ENV_FILE"
}

read_env_default() {
  local key="$1"
  local default_value="$2"
  local value
  value="$(read_env "$key")"
  printf '%s' "${value:-$default_value}"
}

set_env() {
  local file="$1"
  local key="$2"
  local value="$3"
  local tmp="${file}.tmp.$$"

  awk -v key="$key" -v value="$value" '
    BEGIN { done = 0 }
    $0 ~ "^[[:space:]]*" key "=" {
      if (!done) print key "=" value
      done = 1
      next
    }
    { print }
    END { if (!done) print key "=" value }
  ' "$file" > "$tmp"
  chmod --reference="$file" "$tmp" 2>/dev/null || chmod 600 "$tmp"
  mv "$tmp" "$file"
}

append_env_csv_entry() {
  local key="$1"
  local identity="$2"
  local entry="$3"
  local current item normalized
  local -a items=()

  current="$(read_env "$key")"
  IFS=',' read -r -a items <<< "$current"
  for item in "${items[@]}"; do
    normalized="${item#+}"
    normalized="${normalized#-}"
    normalized="${normalized%%=*}"
    if [[ "$normalized" == "$identity" ]]; then
      return
    fi
  done

  if [[ -n "$current" ]]; then
    set_env "$ENV_FILE" "$key" "$current,$entry"
  else
    set_env "$ENV_FILE" "$key" "$entry"
  fi
}

mask_value() {
  local value="$1"
  if [[ -z "$value" ]]; then
    printf '(empty)'
  else
    printf 'set(length=%s)' "${#value}"
  fi
}

require_env_value() {
  local key="$1"
  local label="$2"
  [[ -n "$(read_env "$key")" ]] || fail "missing required env for $label: $key"
}

require_digest() {
  [[ "$TARGET_DIGEST" =~ ^sha256:[0-9a-f]{64}$ ]] \
    || fail "TARGET_DIGEST must be an immutable sha256 digest"
  [[ -n "$TARGET_IMAGE" ]] || fail "TARGET_IMAGE is empty"
}

compose() {
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" "$@"
}

postgres_user() {
  read_env_default POSTGRES_USER paradedb
}

postgres_db() {
  read_env_default POSTGRES_DB lobehub
}

psql_prod() {
  compose exec -T postgresql psql \
    -X -v ON_ERROR_STOP=1 -U "$(postgres_user)" -d "$(postgres_db)" "$@"
}

psql_database() {
  local database="$1"
  shift
  compose exec -T postgresql psql \
    -X -v ON_ERROR_STOP=1 -U "$(postgres_user)" -d "$database" "$@"
}

db_scalar() {
  psql_prod -Atc "$1" | tr -d '[:space:]'
}

verify_local_image_digest() {
  local repo_digests
  require_digest
  repo_digests="$(docker image inspect "$TARGET_IMAGE" --format '{{range .RepoDigests}}{{println .}}{{end}}')"
  grep -Fq "@${TARGET_DIGEST}" <<<"$repo_digests" || {
    echo "Expected: $TARGET_DIGEST" >&2
    echo "Local RepoDigests:" >&2
    printf '%s\n' "${repo_digests:-'(none)'}" >&2
    fail "local image digest does not match the release digest"
  }
  echo "Verified local image digest: $TARGET_DIGEST"
}

verify_platform_management_asset() {
  local asset
  asset="$(
    docker exec "$APP_CONTAINER" /bin/sh -lc \
      'set -eu; find /app/public/_spa/assets -maxdepth 1 -type f -name "platform-analytics-*.js" -print -quit'
  )"
  [[ -n "$asset" ]] || fail "platform management SPA asset is missing"

  if docker exec "$APP_CONTAINER" grep -Fq \
    'NEXT_PUBLIC_COTTI_SHOW_PLATFORM_ANALYTICS' "$asset"; then
    fail "platform management build flag was not compiled into the SPA"
  fi

  echo "platform_management_asset=$(basename "$asset")"
}

required_service_gate() {
  local required_services=(app postgresql qstash searxng)
  local services
  services="$(compose config --services)"

  for service in "${required_services[@]}"; do
    grep -Fqx "$service" <<<"$services" || fail "required Compose service is missing: $service"

    local container_id status health
    container_id="$(compose ps -q --all "$service")"
    [[ -n "$container_id" ]] || fail "required container does not exist: $service"
    status="$(docker inspect "$container_id" --format '{{.State.Status}}')"
    health="$(docker inspect "$container_id" --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}')"
    echo "$service status=$status health=$health"
    [[ "$status" == "running" ]] || fail "required container is not running: $service"

    if [[ "$service" == "app" || "$service" == "postgresql" ]]; then
      [[ "$health" == "healthy" ]] || fail "required container is not healthy: $service"
    fi
  done
}

wait_for_app_health() {
  local status health
  for _ in $(seq 1 120); do
    status="$(docker inspect "$APP_CONTAINER" --format '{{.State.Status}}' 2>/dev/null || true)"
    health="$(docker inspect "$APP_CONTAINER" --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' 2>/dev/null || true)"
    if [[ "$status" == "running" && "$health" == "healthy" ]]; then
      echo "$APP_CONTAINER is running and healthy"
      return 0
    fi
    if [[ "$status" == "exited" || "$status" == "dead" ]]; then
      docker logs --tail 160 "$APP_CONTAINER" >&2 || true
      return 1
    fi
    sleep 2
  done

  docker logs --tail 160 "$APP_CONTAINER" >&2 || true
  return 1
}

wait_for_searxng_health() {
  local status health
  for _ in $(seq 1 60); do
    status="$(docker inspect "$SEARXNG_CONTAINER" --format '{{.State.Status}}' 2>/dev/null || true)"
    health="$(docker inspect "$SEARXNG_CONTAINER" --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' 2>/dev/null || true)"
    if [[ "$status" == "running" && "$health" == "healthy" ]]; then
      echo "$SEARXNG_CONTAINER is running and healthy"
      return 0
    fi
    if [[ "$status" == "exited" || "$status" == "dead" ]]; then
      docker logs --tail 160 "$SEARXNG_CONTAINER" >&2 || true
      return 1
    fi
    sleep 2
  done

  docker logs --tail 160 "$SEARXNG_CONTAINER" >&2 || true
  return 1
}

verify_searxng_search() {
  docker exec "$APP_CONTAINER" /bin/node -e "
const url = 'http://searxng:8080/search?q=LobeHub&format=json&categories=general';
fetch(url, { signal: AbortSignal.timeout(20000) })
  .then(async (response) => {
    if (!response.ok) throw new Error('HTTP ' + response.status);
    const payload = await response.json();
    const count = Array.isArray(payload.results) ? payload.results.length : 0;
    console.log('searxng_results=' + count);
    if (count < 1) process.exit(2);
  })
  .catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
"
}

write_history_fingerprint() {
  local database="$1"
  local output_file="$2"
  local tables=(
    users agents topics messages files documents knowledge_bases user_connectors
    tasks task_topics agent_operations auth_accounts auth_sessions
  )

  : > "$output_file"
  for table in "${tables[@]}"; do
    local exists count
    exists="$(psql_database "$database" -Atc "
      SELECT count(*)
      FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = '${table}';
    " | tr -d '[:space:]')"
    if [[ "$exists" == "1" ]]; then
      count="$(psql_database "$database" -Atc "SELECT count(*) FROM public.\"${table}\";" | tr -d '[:space:]')"
      printf '%s\t%s\n' "$table" "$count" >> "$output_file"
    fi
  done
}

assert_history_not_decreased() {
  local baseline_file="$1"
  [[ -s "$baseline_file" ]] || fail "history fingerprint is missing or empty: $baseline_file"

  # Read the fingerprint before issuing docker compose exec calls. Even with
  # `-T`, docker may consume the loop's stdin and silently skip later rows.
  local -a fingerprint_rows
  mapfile -t fingerprint_rows < "$baseline_file"

  local row table baseline current
  for row in "${fingerprint_rows[@]}"; do
    IFS=$'\t' read -r table baseline <<< "$row"
    [[ -n "$table" && "$baseline" =~ ^[0-9]+$ ]] || fail "invalid fingerprint row for $table"
    current="$(db_scalar "SELECT count(*) FROM public.\"${table}\";")"
    printf '%s baseline=%s current=%s\n' "$table" "$baseline" "$current"
    (( current >= baseline )) || fail "historical row count decreased for $table"
  done
}

assert_no_recent_active_runs() {
  local active_operations active_task_topics
  active_operations="$(db_scalar "
    SELECT count(*) FROM agent_operations
    WHERE status='running'
      AND coalesce(started_at, created_at) >= now() - interval '4 hours';
  ")"
  active_task_topics="$(db_scalar "
    SELECT count(*) FROM task_topics
    WHERE status='running'
      AND updated_at >= now() - interval '4 hours';
  ")"
  echo "recent_running_agent_operations=$active_operations"
  echo "recent_running_task_topics=$active_task_topics"
  [[ "$active_operations" == "0" && "$active_task_topics" == "0" ]] \
    || fail "recent Agent or Task runs are active; wait for completion before release"
}

write_release_state_value() {
  local key="$1"
  local value="$2"
  local state_file="$RELEASE_STATE_FILE"
  if [[ ! -f "$state_file" ]]; then
    install -m 600 /dev/null "$state_file"
  fi
  set_env "$state_file" "$key" "$value"
}
